// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.237
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Column name converts by convention to nicely formatted property name")]
    public partial class ColumnNameConvertsByConventionToNicelyFormattedPropertyNameFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ColumnNameToPropertyConventions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Column name converts by convention to nicely formatted property name", "As a developer\r\nI want my dynamic code to follow common conventions\r\nSo that I kn" +
                    "ow how to access them", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Single word in columns are left untouched")]
        public virtual void SingleWordInColumnsAreLeftUntouched()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single word in columns are left untouched", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "age"});
            table1.AddRow(new string[] {
                        "Marcus",
                        "39"});
#line 8
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table1);
#line 11
 testRunner.Then("the Name property should equal \'Marcus\'");
#line 12
  testRunner.And("the age property should equal 39");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Two word in the column headers is converted to camel cased properties")]
        public virtual void TwoWordInTheColumnHeadersIsConvertedToCamelCasedProperties()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Two word in the column headers is converted to camel cased properties", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Birth date",
                        "Length in meters"});
            table2.AddRow(new string[] {
                        "1972-10-09",
                        "1.96"});
#line 15
 testRunner.When("I create a dynamic instance from this table", ((string)(null)), table2);
#line 18
 testRunner.Then("the BirthDate property should equal 1972-10-09");
#line 19
  testRunner.And("the LengthInMeters property should equal 1.96");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Even if you go crazy with naming you columns we try to shape it up")]
        public virtual void EvenIfYouGoCrazyWithNamingYouColumnsWeTryToShapeItUp()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Even if you go crazy with naming you columns we try to shape it up", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Birth dAtE",
                        "Length IN mETERs"});
            table3.AddRow(new string[] {
                        "1972-10-09",
                        "1.96"});
#line 22
 testRunner.When("I create a dynamic instance from this table", ((string)(null)), table3);
#line 25
 testRunner.Then("the BirthDate property should equal 1972-10-09");
#line 26
  testRunner.And("the LengthInMeters property should equal 1.96");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("But the first word is always left untouched since it might be abbreviations")]
        public virtual void ButTheFirstWordIsAlwaysLeftUntouchedSinceItMightBeAbbreviations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("But the first word is always left untouched since it might be abbreviations", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "SAT score"});
            table4.AddRow(new string[] {
                        "Have no idea what an SAT should be",
                        "132"});
#line 29
 testRunner.When("I create a dynamic instance from this table", ((string)(null)), table4);
#line 32
 testRunner.Then("the SATScore should be 132");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
