// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.7.1.0
//      SpecFlow Generator Version:1.7.0.0
//      Runtime Version:4.0.30319.237
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.7.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Comparing dynamic instances")]
    public partial class ComparingDynamicInstancesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ComparingDynamicInstances.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Comparing dynamic instances", "In order to be able to easy do assertions\r\nAs a SpecFlow developer\r\nI want to be " +
                    "able to compare dynamic instances", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Matching a dynamic instance against a table")]
        public virtual void MatchingADynamicInstanceAgainstATable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Matching a dynamic instance against a table", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Age",
                        "Birth date",
                        "Length in meters"});
            table1.AddRow(new string[] {
                        "Marcus",
                        "39",
                        "1972-10-09",
                        "1.96"});
#line 7
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Age",
                        "Birth date",
                        "Length in meters"});
            table2.AddRow(new string[] {
                        "Marcus",
                        "39",
                        "1972-10-09",
                        "1.96"});
#line 10
 testRunner.When("I compare it to this table", ((string)(null)), table2);
#line 13
 testRunner.Then("no exception should have been thrown");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Not matching when 1 header differ")]
        public virtual void NotMatchingWhen1HeaderDiffer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Not matching when 1 header differ", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table3.AddRow(new string[] {
                        "Marcus"});
#line 16
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table3);
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "N"});
            table4.AddRow(new string[] {
                        "Marcus"});
#line 19
 testRunner.When("I compare it to this table", ((string)(null)), table4);
#line 22
 testRunner.Then("an difference exception should be thrown with 2 differences");
#line 23
  testRunner.And("one difference should be on the \'Name\' field of the instance");
#line 24
  testRunner.And("one difference should be on the \'N\' column of the table");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Not matching when 2 header differ")]
        public virtual void NotMatchingWhen2HeaderDiffer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Not matching when 2 header differ", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Birth date"});
            table5.AddRow(new string[] {
                        "Marcus",
                        "2000-01-01"});
#line 27
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "N",
                        "Date of birth"});
            table6.AddRow(new string[] {
                        "Marcus",
                        "2000-01-01"});
#line 30
 testRunner.When("I compare it to this table", ((string)(null)), table6);
#line 33
 testRunner.Then("an difference exception should be thrown with 4 differences");
#line 34
  testRunner.And("one difference should be on the \'Name\' field of the instance");
#line 35
  testRunner.And("one difference should be on the \'BirthDate\' field of the instance");
#line 36
  testRunner.And("one difference should be on the \'N\' column of the table");
#line 37
  testRunner.And("one difference should be on the \'DateOfBirth\' column of the table");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Not matching when 1 value differ")]
        public virtual void NotMatchingWhen1ValueDiffer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Not matching when 1 value differ", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table7.AddRow(new string[] {
                        "Marcus"});
#line 40
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table7);
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table8.AddRow(new string[] {
                        "Albert"});
#line 43
 testRunner.When("I compare it to this table", ((string)(null)), table8);
#line 46
 testRunner.Then("an difference exception should be thrown with 1 difference");
#line 47
  testRunner.And("one difference should be on the \'Name\' property");
#line 48
  testRunner.And("one message should state that the instance had the value \'Marcus\'");
#line 49
  testRunner.And("one message should state that the table had the value \'Albert\'");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Not matching when several value differ")]
        public virtual void NotMatchingWhenSeveralValueDiffer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Not matching when several value differ", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "BirthDate",
                        "LengthInMeters"});
            table9.AddRow(new string[] {
                        "Marcus",
                        "1972-10-09",
                        "1.96"});
#line 52
 testRunner.Given("I create a dynamic instance from this table", ((string)(null)), table9);
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Birth date",
                        "Length in meters"});
            table10.AddRow(new string[] {
                        "Albert",
                        "2008-01-24",
                        "1.04"});
#line 55
 testRunner.When("I compare it to this table", ((string)(null)), table10);
#line 58
 testRunner.Then("an difference exception should be thrown with 3 difference");
#line 59
  testRunner.And("one difference should be on the \'Name\' property");
#line 60
  testRunner.And("one difference should be on the \'BirthDate\' property");
#line 61
  testRunner.And("one difference should be on the \'LengthInMeters\' property");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#endregion
